// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfKn54BXWgGfgjhiNnBC_xYO23QZfaWHI',
    appId: '1:61255138479:web:32fc3d06af653c8590e85a',
    messagingSenderId: '61255138479',
    projectId: 'sigaapp-127c4',
    authDomain: 'sigaapp-127c4.firebaseapp.com',
    databaseURL: 'https://sigaapp-127c4-default-rtdb.firebaseio.com',
    storageBucket: 'sigaapp-127c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1Qf4ZOj2Shs7azW96Gp5j9zB_Q-WLcY',
    appId: '1:61255138479:android:85dd207b13829d0590e85a',
    messagingSenderId: '61255138479',
    projectId: 'sigaapp-127c4',
    databaseURL: 'https://sigaapp-127c4-default-rtdb.firebaseio.com',
    storageBucket: 'sigaapp-127c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvQBy3oofNUC1teLo1ztlKcojBl0CgTfk',
    appId: '1:61255138479:ios:f9718277a5696f5890e85a',
    messagingSenderId: '61255138479',
    projectId: 'sigaapp-127c4',
    databaseURL: 'https://sigaapp-127c4-default-rtdb.firebaseio.com',
    storageBucket: 'sigaapp-127c4.appspot.com',
    iosClientId: '61255138479-ildgl933lm7c68tkg0l943ru7n1itjs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigalogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvQBy3oofNUC1teLo1ztlKcojBl0CgTfk',
    appId: '1:61255138479:ios:f9718277a5696f5890e85a',
    messagingSenderId: '61255138479',
    projectId: 'sigaapp-127c4',
    databaseURL: 'https://sigaapp-127c4-default-rtdb.firebaseio.com',
    storageBucket: 'sigaapp-127c4.appspot.com',
    iosClientId: '61255138479-ildgl933lm7c68tkg0l943ru7n1itjs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigalogin',
  );
}
